# Pull Requests for GitHub repository settings https://github.com/apps/settings
repository:
  # A short description of the repository that will show up on GitHub
  description: repository template for github

  # A URL with more information about the repository
  homepage: 

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: master

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: false

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: "Type: Bug"
    color: ee0701
  - name: "Type: Documentation"
    color: 5319e7
  - name: "Type: Enhancement"
    color: 1d76db
  - name: "Type: Maintenance"
    color: fbca04
  - name: "Type: Question"
    color: cc317c
  - name: "Priority: Critical"
    color: ee0701
  - name: "Priority: High"
    color: d93f0b
  - name: "Priority: Medium"
    color: fbca04
  - name: "Priority: Low"
    color: 0e8a16
  - name: "Status: Abandoned"
    color: 000000
  - name: "Status: Available"
    color: c2e0c6
  - name: "Status: Blocked"
    color: ee0701
  - name: "Status: In Progress"
    color: cccccc
  - name: "Status: On Hold"
    color: e99695
  - name: "Status: Proposal"
    color: d4c5f9
  - name: "Status: Review Needed"
    color: fbca04
# Add areas by using the following template
#  - name: "Area: API
#    color: ffffff
